# Use the official Node.js image.
# https://hub.docker.com/_/node
FROM node:18 AS build

# Create and change to the app directory.
WORKDIR /usr/src/app

# Copy application dependency manifests to the container image.
COPY package*.json ./

# Install all dependencies.
RUN npm install

# Copy the application code to the container image.
COPY . .

# Build the app for production.
RUN npm run build

# Expose port 80 for the app.
EXPOSE 80

# Run the web server on container startup.
CMD ["npm", "start"]